name: Python Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # You can specify the version you need

    - name: Install distutils (if needed)
      run: sudo apt-get install python3-distutils

    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Run your tests
      run: |
        # Add your test commands here
        python -m unittest discover  # Example test command
